version: "3.9"

services:
  strapi:
    image: strapi/strapi
    restart: always
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=strapidb
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    depends_on:
      - strapidb

  strapidb:
    restart: always
    image: mariadb:10.5.8-focal
    restart: always
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - strapidb:/var/lib/mysql

  wordpress:
    image: wordpress:5.6.1-apache
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpressdb

  wordpressdb:
    restart: always
    image: mariadb:10.5.8-focal
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - wordpressdb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  strapidb:
    external: true
  wordpress:
    external: true
  wordpressdb:
    external: true